Repository Remulus2006/Novelidea, pull requests merged in 2019-01, with the labels that each got.

#19 StoryLibrary and Images Change
  BrainyStories/BrainyStories/BrainyStories.Android/BrainyStories.Android.csproj
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/Resource.designer.cs
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/ClassicStories.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Imagines.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Progress.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Quizzes.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Rewards.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/ThinkAndDo.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/classicStories2.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/imagines2.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/progress2.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/quizzes3.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/rewards2.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/thinkAndDos2.png
  BrainyStories/BrainyStories/BrainyStories/MainPage.xaml
  BrainyStories/BrainyStories/BrainyStories/StoryFactory.cs
  BrainyStories/BrainyStories/BrainyStories/TableOfContents.xaml.cs
  BrainyStories/BrainyStories/BrainyStories/story.cs
Labels: enhancement

#24 Added Imagines List to simple TOC
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/Resource.designer.cs
  BrainyStories/BrainyStories/BrainyStories/TableOfContents.xaml.cs
Labels: clean code

#26 Simple toc
  BrainyStories/BrainyStories/BrainyStories.Android/BrainyStories.Android.csproj
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/Resource.designer.cs
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Animal.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Female.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/General.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Male.png
  BrainyStories/BrainyStories/BrainyStories/StoryFactory.cs
  BrainyStories/BrainyStories/BrainyStories/TableOfContents.xaml
  BrainyStories/BrainyStories/BrainyStories/TableOfContents.xaml.cs
  BrainyStories/BrainyStories/BrainyStories/story.cs
Labels: Feature
