Repository Remulus2006/Novelidea, pull requests merged in 2019-03, with the labels that each got.

#47 Quiz functionality
  BrainyStories/BrainyStories/BrainyStories/Objects/Quiz.cs
  BrainyStories/BrainyStories/BrainyStories/QuizFactory.cs
  BrainyStories/BrainyStories/BrainyStories/QuizPage.xaml
  BrainyStories/BrainyStories/BrainyStories/QuizPage.xaml.cs
  BrainyStories/BrainyStories/BrainyStories/StoryPage.xaml.cs
Labels: Feature

#48 Progress page
  BrainyStories/BrainyStories/BrainyStories.Android/BrainyStories.Android.csproj
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/Resource.designer.cs
  BrainyStories/BrainyStories/BrainyStories.iOS/BrainyStories.iOS.csproj
  BrainyStories/BrainyStories/BrainyStories/BrainyStories.csproj
  BrainyStories/BrainyStories/BrainyStories/MainPage.xaml.cs
  BrainyStories/BrainyStories/BrainyStories/Objects/User.cs
  BrainyStories/BrainyStories/BrainyStories/ProgressPage.xaml
  BrainyStories/BrainyStories/BrainyStories/ProgressPage.xaml.cs
Labels: Feature, user interface

#49 Bug fixes
  BrainyStories/BrainyStories/BrainyStories.Android/MainActivity.cs
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/BackButton.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Home.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/SettingsButton.png
  BrainyStories/BrainyStories/BrainyStories/MainPage.xaml
  BrainyStories/BrainyStories/BrainyStories/QuizPage.xaml
  BrainyStories/BrainyStories/BrainyStories/StoryPage.xaml.cs
  BrainyStories/BrainyStories/BrainyStories/TableOfContents.xaml.cs
  BrainyStories/BrainyStories/BrainyStories/ThinkAndDoList.xaml.cs
Labels: bug

#52 Insert quiz info
  BrainyStories/BrainyStories/BrainyStories/QuizFactory.cs
  BrainyStories/BrainyStories/BrainyStories/StoryFactory.cs
  BrainyStories/BrainyStories/BrainyStories/StoryPage.xaml.cs
Labels: Feature

#55 Quiz page
  BrainyStories/BrainyStories/BrainyStories/BrainyStories.csproj
  BrainyStories/BrainyStories/BrainyStories/MainPage.xaml
  BrainyStories/BrainyStories/BrainyStories/MainPage.xaml.cs
  BrainyStories/BrainyStories/BrainyStories/Objects/Quiz.cs
  BrainyStories/BrainyStories/BrainyStories/QuizFactory.cs
  BrainyStories/BrainyStories/BrainyStories/QuizList.xaml
  BrainyStories/BrainyStories/BrainyStories/QuizList.xaml.cs
Labels: Feature

#58 Put in and updated icon images for stories so standardized
  BrainyStories/BrainyStories/BrainyStories.Android/BrainyStories.Android.csproj
  BrainyStories/BrainyStories/BrainyStories/QuizFactory.cs
  BrainyStories/BrainyStories/BrainyStories/StoryFactory.cs
  BrainyStories/BrainyStories/BrainyStories/ThinkAndDoFactory.cs
Labels: clean code

#59 Changed times of Think and Dos
  BrainyStories/BrainyStories/BrainyStories/ThinkAndDoFactory.cs
Labels: bug, clean code
