Repository Remulus2006/Novelidea, pull requests merged in 2019-04, with the labels that each got.

#63 Fix quiz times, quiz number, TAD number
  BrainyStories/BrainyStories/BrainyStories/QuizFactory.cs
  BrainyStories/BrainyStories/BrainyStories/StoryFactory.cs
  BrainyStories/BrainyStories/BrainyStories/ThinkAndDoFactory.cs
Labels: clean code

#65 Input new images for rewards
  BrainyStories/BrainyStories/BrainyStories.Android/BrainyStories.Android.csproj
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/Resource.designer.cs
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Bank.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Coin.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Coins.png
  BrainyStories/BrainyStories/BrainyStories.Android/Resources/drawable/Gem.png
  BrainyStories/BrainyStories/BrainyStories/RewardsPage.xaml
  BrainyStories/BrainyStories/BrainyStories/RewardsPage.xaml.cs
Labels: Feature

#69 Background
  BrainyStories/BrainyStories/BrainyStories/EndOfStory.xaml
  BrainyStories/BrainyStories/BrainyStories/MainPage.xaml
  BrainyStories/BrainyStories/BrainyStories/ProgressOverallPage.xaml
  BrainyStories/BrainyStories/BrainyStories/ProgressPage.xaml
  BrainyStories/BrainyStories/BrainyStories/ProgressSummaryPage.xaml
  BrainyStories/BrainyStories/BrainyStories/QuizList.xaml
  BrainyStories/BrainyStories/BrainyStories/QuizPage.xaml
  BrainyStories/BrainyStories/BrainyStories/RewardsPage.xaml
  BrainyStories/BrainyStories/BrainyStories/Settings.xaml
  BrainyStories/BrainyStories/BrainyStories/StoryPage.xaml
  BrainyStories/BrainyStories/BrainyStories/TableOfContents.xaml
  BrainyStories/BrainyStories/BrainyStories/ThinkAndDoList.xaml
Labels: user interface
